server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, circuitbreakers, circuitbreakerevents, refresh
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    circuitbreakers:
      enabled: true
    env:
      show-values: ALWAYS

# 로깅 설정
logging:
  level:
    com.example.springboot: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.config: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"